return {}
-- return {
--   'nvim-orgmode/orgmode',
--   event = 'VeryLazy',
--   ft = { 'org' },
--   config = function()
--     -- Setup orgmode
--     require('orgmode').setup {
--       org_agenda_files = '~/orgfiles/**/*',
--       org_default_notes_file = '~/orgfiles/refile.org',
--       org_todo_keywords = { 'TODO(t)', 'WIP(w)', 'IN_PROGRESS(p)', '|', 'DONE(d)' },
--       org_capture_templates = {
--         t = {
--           description = 'Todo',
--           template = '* TODO %?\n %u',
--           target = '~/orgfiles/todos.org',
--         },
--         n = {
--           description = 'Note',
--           template = '\n*** %<%Y-%m-%d> %<%A> \n**** %U\n\n%?',
--           target = '~/orgfiles/nodes.org',
--         },
--         w = {
--           description = 'WIP',
--           target = '~/orgfiles/wip.org',
--           template = table.concat({
--             '* WIP %? :wip:',
--             "  [[%(return 'file://' .. vim.fn.expand('%:p') .. '::' .. vim.fn.line('.'))][%(return vim.fn.expand('%:t')):%(return vim.fn.line('.'))]]",
--           }, '\n'),
--         },
--         W = {
--           description = 'WIP',
--           target = '~/orgfiles/wip.org',
--           template = table.concat {
--             '* WIP %? :wip:',
--             '[[file:%F::%l][:f:%l]]',
--           },
--         },
--       },
--       mapping = {
--         agenda = {
--           org_agenda_todo = '<C-Space>',
--         },
--         org = {
--           org_toggle_checkbox = false,
--         },
--       },
--     }
--
--     -- Experimental LSP support
--     vim.lsp.enable 'org'
--
--     vim.keymap.set('n', '<leader>;', function() vim.cmd.edit(vim.fn.expand '~/orgfiles/') end, { desc = 'Open notes' })
--   end,
-- }
