return {}
-- return {
--   'nvim-orgmode/telescope-orgmode.nvim',
--   event = 'VeryLazy',
--   dependencies = {
--     'nvim-orgmode/orgmode',
--     'folke/snacks.nvim',
--   },
--   config = function()
--     local tom = require 'telescope-orgmode'
--     tom.setup { adapter = 'snacks' }
--
--     vim.keymap.set('n', '<leader>fh', tom.search_headings, { desc = 'Org headlines' })
--     vim.keymap.set('n', '<leader>ft', tom.search_tags, { desc = 'Org tags' })
--     vim.keymap.set('n', '<leader>r', tom.refile_heading, { desc = 'Org refile' })
--     -- vim.keymap.set('n', '<leader>li', tom.insert_link, { desc = 'Org insert link' })
--     --
--     vim.api.nvim_create_user_command('WIP', function()
--       local items = {}
--       for _, heading in ipairs(tom.search_tags { tags = 'wip' }) do
--         local text = heading:get_text()
--
--         local file, line = text:match '%[%[file:(.-)::(%d+)%]%['
--         if file and line then table.insert(items, {
--           filename = file,
--           lnum = tonumber(line),
--           text = heading.title,
--         }) end
--       end
--       vim.fn.setqflist({}, ' ', {
--         title = 'Org WIP',
--         items = items,
--       })
--
--       vim.cmd.copen()
--     end, { desc = 'Open wips' })
--   end,
-- }
